image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  only:
    - master
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq lftp
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $HOST; mirror -Rev dist/ .  --ignore-time --parallel=10    --exclude-glob .git* --exclude .git/"
  only:
    - master
