image: node:latest

before-script:
  - apt-get update -qq && apt-get install -y -qq lftp
  - npm install

script:
  - npm build
  - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $HOST; mirror -Rev dist/ ./public_html  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
